version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:8080

#   Valido solo para desarrollo local.
#        depends_on:
#            - database
#    database:
#        container_name: database
#        image: mysql:8.0
#        ports:
#            - 3306:3306
#        environment:
#            - MYSQL_DATABASE=dirtelex
#            - MYSQL_USER=admin
#            - MYSQL_PASSWORD=123456
#            - MYSQL_ROOT_PASSWORD=123456
#        volumes:
#            - db-data:/var/lib/mysql
#volumes:
#    db-data: ~
